# Este archivo NO debe subirse a repos públicos.
# Usa Streamlit Cloud Secrets en producción.
SHEET_ID = "REEMPLAZA_CON_TU_ID_DE_SHEET"
# Pega el JSON COMPLETO de tu service account entre comillas triples:
gservice_account = """{ "type": "service_account", "project_id": "..."}"""
